

typedef struct _asn1_obj_t {
	uint8_t tag;
	size_t len;
	uint8_t *data;
} asn1_obj_t;

enum ASN1_TYPES {
	ANS1_RESVD = 0,
	ANS1_BOOLEAN,
	ANS1_INTEGER,
	ANS1_BITSTRING,
	ANS1_OCTETSTRING,
	ANS1_NULL,
	ANS1_OBJECTID,
	ANS1_OBJECTDESC,
	ANS1_INSTANCE,
	ANS1_REAL,
	ANS1_ENUMERATED,
	ASN1_EMBEDDEDPDV,
	ASN1_UTF8STRING,
	ASN1_RELATIVEOID,
	ASN1_SEQUENCE = 16,
	ASN1_SET,
	ASN1_NUMERICSTRING,
	ASN1_PRINTABLESTRING,
	ASN1_TELETEXSTRING,
	ASN1_VIDEOTEXSTRING,
	ASN1_IA5STRING,
	ASN1_UTCTIME,
	ASN1_GENERALIZEDTIME,
	ASN1_GRAPHICSTRING,
	ASN1_VISIBLESTRING,
	ASN1_GENERALSTRING,
	ASN1_UNIVERSALSTRING,
	ASN1_CHARSTRING,
	ASN1_BMPSTRING
};

size_t asn1_decode(void *asn1_data, size_t asn1_len, asn1_obj_t *objs, size_t iter_count);
